project:
  type: website
  output-dir: docs

website:
  title: "Geospatial Analysis in R and Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    search: true
    background: "#D4E9E0"
    collapse-level: 1
    contents:
        - section: "<b>MENU</b>"
          contents: 
        - section: "R in RStudio"
        - section: "R in Colab"
          contents:
            - text: "ggplot2"
              href: R_Titanic_Data_ggplot2.html
        - section: "Python in Colab"
          contents:
            - text: "Data Import-Export"
              href: python-data-import-export.qmd
          
  page-footer:
    center: 
      - text: "Â© CC-By Md.Shiful Islam, Senior Scientific Officer, Soil Resource Development Institute, Bangladesh 2023</br> R Script Credit: Zia Ahmed, Unversity at Buffalo"
format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    code-fold: true
    highlight-style: atom-one
    code-block-bg: "#DBDBDB"
    code-block-border-left: "#5A5A5A"
    backgroundcolor: "#F4E0DF"

editor: visual


