project:
  type: website
  output-dir: docs

website:
  title: "Geospatial Analysis in R and Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
  page-footer:
    center: 
      - text: "Â© CC-By Md.Shiful Islam, Senior Scientific Officer, Soil Resource Development Institute, Bangladesh 2023</br> R Script Credit: Zia Ahmed, Unversity at Buffalo"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


